name: Run Newman Collection

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-newman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Newman and HTMLExtra Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Newman Collection with HTMLExtra Reporter
        id: newman-run
        run: |
          newman run CrispAssignment.postman_collection.json \
            -e QA.postman_environment.json \
            -d testdata.csv \
            -r htmlextra \
            --reporter-htmlextra-export newman-report.html

      - name: Archive Report with Success Name
        if: always() && success()
        uses: actions/upload-artifact@v3
        with:
          name: newman-html-report-success
          path: newman-report.html

      - name: Archive Report with Failure Name
        if: always() && failure()
        uses: actions/upload-artifact@v3
        with:
          name: newman-html-report-failure
          path: newman-report.html
